version: "3.9"

volumes:
    clickhouse_data:

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        command: ["nginx-debug", "-g", "daemon off;"]

    fpm:
        image: php:8.3.0-fpm-xdebug
        build: 
          context: php
        volumes:
            - ./src:/var/www/html
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    ch:
        image: clickhouse/clickhouse-server:22.8
        volumes:
            - clickhouse_data:/var/lib/clickhouse
